### ISSUE TITLE
Farming helper / counter

### ISSUE THREAD

**Issue by Primajin** [chiyadev/genshin-schedule#116]
I have an idea for a farming helper.
Let's say one needs six Famed Handguards.
Now you start fighting and farming and gather Old Handguards alongside Kageuchi Handguards.
Three of each can always transmuted into one higher level.
So now you can just tick a button whenever you get one of the three Handguards, and it will automatically count up for you with factoring in the transmutation count.

Let's say this is your current inventory

| Handguard | Amount |
| --- | --- |
| Old | III III II |
| Kageuchi | III I |
| Famed (6) | III |

Now you find one Old and one Kageuchi from an enemy

| Handguard | Amount |
| --- | --- |
| Old | III III III |
| Kageuchi | III II |
| Famed (6) | III |

Which can be transmuted to

| Handguard | Amount |
| --- | --- |
| Old |  |
| Kageuchi | III III II |
| Famed (6) | III |

| Handguard | Amount |
| --- | --- |
| Old |  |
| Kageuchi | II |
| Famed (6) | III II |

So you can see that you just need either 3 more Old ones or one more Kageuchi to have the 6 Famed.

**Comment by luaneko** [comment]
I had this idea before. I think the overhead in keeping your inventory items and the website in sync makes painful to use in practice. Unless there is a way to programmatically retrieve player inventory (which there isn't,) I don't think many people would use it.

**Comment by Primajin** [comment]
And if we iterate on it? I think it's already helpful when we just have the tool in place and then setting up your current inventory will only take a couple of seconds by manually clicking the `[+1]` buttons a couple of times.

Syncing and persistence layers can be added in later steps.

**Comment by luaneko** [comment]
I think you are underestimating the amount of items an average player has in their inventory. There is a lot of items to go through in order to keep the website in sync, and if you ever forget to update the website after collecting a specific item, you would have to go through the entire list again to make sure everything is correct.

I think a better approach would be to implement a calculator-like feature into which you can enter how many of each rarity of an item you currently have, and then it calculates how many more of each rarity you would need to reach a certain count. Though, the usefulness of such a feature is also questionable as it can also be done by simply putting a few numbers into a calculator.

**Comment by Primajin** [comment]
Yes I was more after the latter.

How about I build a tiny codesandbox, link it here and then we check if such a tool would make sense to integrate or not. 👍🏻

**Comment by Primajin** [comment]
I was thinking of something very basic like this:
Demo: https://rhrnuc.csb.app/
Code: https://codesandbox.io/s/morning-bash-rhrnuc?file=/src/App.js
![farm-help](https://user-images.githubusercontent.com/1742115/166435140-25caa50d-47bc-47da-8f67-268a39558481.gif)

**Comment by Primajin** [comment]
I added another little feature idea - to lock individual tiers (in case you need 18 blue and don't want it to auto calculate) and to limit by three tiers (for some talent material there is no golden tier)

![lock-and-limit](https://user-images.githubusercontent.com/1742115/169327189-dacc38d7-ed1d-456e-87bc-9079a3729f2f.gif)

**Comment by Primajin** [comment]
Also introduced grey tier to make it more obvious when there is three vs. four tiers.
![handguard-gemstone](https://user-images.githubusercontent.com/1742115/169541543-8058d5bc-074a-44ad-9efe-c25012e26c17.gif)

**Comment by Primajin** [comment]
Added icons and improved rounding when unlocking a field with a number not dividable by three.

![image](https://user-images.githubusercontent.com/1742115/169658832-4535e355-e3d7-48e4-b3f2-672084380e7a.png)

**Comment by Primajin** [comment]
Alright I moved it into it's own App:
App: https://primajin.github.io/genshin-farming-helper
Code: https://github.com/Primajin/genshin-farming-helper

![image](https://user-images.githubusercontent.com/1742115/185748078-c5098b79-8c73-429f-a116-fe912b63307a.png)
