### ISSUE TITLE
[Feature Request] Expedition Timer

### ISSUE THREAD

**Issue by lostguru** [chiyadev/genshin-schedule#14]
Thanks for the site! It's been super useful.

Would it be possible to add an expedition timer module? Something along the lines of "clicking this button starts a 20 hour timer that counts down to zero" would be useful. Obviously there'd be other stuff that could be fleshed out (decreased times for characters with expedition passives, a separate entry and timer for each character out on expedition, etc.) but at its core it'd just be a countdown timer.

I guess another request might be to add the ability to reorder the modules on the page, but that would likely be a bit more involved to implement depending on how the page is laid out.

**Comment by luaneko** [comment]
Implementing these features should be easy, but personally I don't think expedition timer would be useful because you always have to open the game at least once every 16 hours to spend resin anyway. You would know that expeditions are complete without having to check the website.

**Comment by bzz3** [comment]
That's fair. Appreciate the response!

**Comment by lostguru** [comment]
That's fair. Appreciate the response!

**Comment by luaneko** [comment]
I think this can be done using the [Reminder's System](https://github.com/chiyadev/genshin-schedule/issues/30) proposal.
