### ISSUE TITLE
login

### ISSUE THREAD

**Issue by DemonRem** [chiyadev/genshin-schedule#16]
how i can sign in to the website?

**Comment by luaneko** [comment]
You can sign in or register by filling this form in the homepage and clicking Submit.

![6177083E-7D6D-42F1-99B4-F04A690AF5D4](https://user-images.githubusercontent.com/27663662/100545274-22d54580-32af-11eb-87d1-4ef8a5c2f71f.jpeg)

If you don't see this form, try signing out by going to the Customize page and scrolling to the bottom.
