### ISSUE TITLE
Resin Input Cropping Itself on Refresh

### ISSUE THREAD

**Issue by ImmortalZypther** [chiyadev/genshin-schedule#2]
The input for resin will lower its max-width CSS by a couple pixels whenever you refresh the page.
This almost always ends up cutting off the number when you come back to the page later.
![image](https://user-images.githubusercontent.com/21045587/97095732-30087000-1631-11eb-9456-3e78f1f5d44d.png)

**Comment by luaneko** [comment]
This is a problem I recognized as well. It's caused by the browser not loading Bonobo (website font) immediately after page load.

**Comment by luaneko** [comment]
This should be fixed now. If you could please confirm it, that would be great~

**Comment by ImmortalZypther** [comment]
Seems inconsistently fixed at the moment, sometimes when I open the page or refresh the issue shows up again.
It isn't very rare either, took less than half a minute to get another picture.
![image](https://user-images.githubusercontent.com/21045587/97108434-e7d66580-16a3-11eb-9725-d71ff4e4c88e.png)

**Comment by luaneko** [comment]
Which browser and version are you using?

**Comment by ImmortalZypther** [comment]
Google Chrome Version 86.0.4240.111 (Official Build) (64-bit)

**Comment by luaneko** [comment]
I've pushed another fix for this, can you confirm this issue again?

**Comment by ImmortalZypther** [comment]
Spent around a minute spamming refresh, looks fixed to me!

Side note, thanks so much for responding quickly to all the issues I've posted here. 
I kinda felt bad seeing I was the only person asking for stuff to be added/changed/fixed.

**Comment by luaneko** [comment]
It's all good. You don't need to feel bad about it, I've also received multiple requests from other sources so you're not the only one~
