### ISSUE TITLE
Resin Calculator subtraction buttons can no longer be clicked on in Brave browser

### ISSUE THREAD

**Issue by lostguru** [chiyadev/genshin-schedule#20]
Low priority, since this issue only seems to happen while using the Brave browser.

https://i.imgur.com/ZHJQBCA.gif

Works fine in Google Chrome and Mozilla Firefox.

**Comment by luaneko** [comment]
As a workaround, you should still be able to manually type into the calculator by clicking on the number.

**Comment by lostguru** [comment]
Yeah, been doing just that.

Would it be possible to also add keyboard shortcuts for those subtraction commands?

**Comment by luaneko** [comment]
Sure, let's keep this issue focused on the Brave browser bug and create a new issue.

**Comment by luaneko** [comment]
Which version of Brave browser are you using? I cannot reproduce this issue on the latest release. Can you try updating and restarting the browser and see if the problem persists?

`Version 1.17.75 Chromium: 87.0.4280.88 (Official Build) (64-bit)`

**Comment by lostguru** [comment]
Same Brave version. Restarting the browser/computer didn't fix the issue the past two days I was having it, but with your most recent update it looks like it fixed itself. It was probably something on my end I couldn't track down, so I'll close the issue. Sorry for your time.
