### ISSUE TITLE
Keyboard shortcuts for Resin Calculator subtraction functions

### ISSUE THREAD

**Issue by bzz3** [chiyadev/genshin-schedule#22]
No preference on what keys are chosen. `2`, `4`, and `6` and their Numpad variants would be intuitive, but a check would be needed to make sure the text box isn't currently active.

**Comment by luaneko** [comment]
Added!

![image](https://user-images.githubusercontent.com/27663662/101227342-9d58f780-36eb-11eb-898e-4659427d5877.png)
