### ISSUE TITLE
Feature Request: Resin Calculator Thresholds

### ISSUE THREAD

**Issue by ImmortalZypther** [chiyadev/genshin-schedule#3]
Currently, resin events are fairly general with the amounts of resin they require. 
They either need 20, 40, or 60.

I think it'd be useful to have the resin calculator show how long until you reach those thresholds if you're below them just so you know how long it'll be until you can run the next domain, weekly boss, elite boss, etc.

For example: if you're at 12 resin, it'll say "20 resin in 1 hour 4 minutes" and "40 resin in 3 hours 44 minutes"

This could potentially even replace what the calculator currently does by keeping track of intervals of 15.

**Comment by luaneko** [comment]
This could be a non-default configurable option. Personally, I find it much more useful to show whole hours instead, when e.g. checking the amount of resin I will have after I sleep for 8 hours.

**Comment by luaneko** [comment]
This has been implemented! You can click on the resin icon to change estimation mode.
![image](https://user-images.githubusercontent.com/27663662/97147570-d1bcc800-17bd-11eb-8c85-6778742451fe.png)
