### ISSUE TITLE
Missing Enter the Golden House domain

### ISSUE THREAD

**Issue by luaneko** [chiyadev/genshin-schedule#35]
While reviewing #34 I realized that [Enter the Golden House](https://genshin-impact.fandom.com/wiki/Enter_the_Golden_House) trounce domain is also missing from the domain list.

Low-prio as it works the exact same way as Confront Stormterror and Wolf of the North Challenge right now.

**Comment by lauslim12** [comment]
Could I take this on after #36 is solved? Thank you!
