### ISSUE TITLE
[Feature Request] Alternate Resin timing

### ISSUE THREAD

**Issue by NissaCam** [chiyadev/genshin-schedule#47]
The Resin calculator is super handy - I use it all the time. But it would be even more helpful if it could also show (or be set to show) when you'll hit relevant amounts of resin (as opposed to how much resin you'll have in certain amounts of time). Basically, how long until you hit any given multiple of 20 so you know when you can hit your next domain, boss, etc.

This would be even better if you could set your time zone and see what time you'll hit these milestones, and best of all if you could set reminders for them with the reminders bot (ping me whenever I have 40 resin available, for instance)

**Comment by luaneko** [comment]
> if you could set reminders for them with the reminders bot (ping me whenever I have 40 resin available, for instance)

This bit is already possible, see #27.

**Comment by Primajin** [comment]
Exactly what I was going to request as well :D 

EDIT: Hey there it is already - found it in the code:
![image](https://user-images.githubusercontent.com/1742115/110006259-b63c6d80-7d19-11eb-84f8-77f9ac50ca0c.png)

But it seems the corresponding setting is missing 🤔

**Comment by Primajin** [comment]
Gladly your code is super well structured, so I could quickly patch up #50 🎉

**Comment by Primajin** [comment]
@NissaCam for now you can go to `Customize` > `Manage Data` and carefully edit `resinEstimateMode` from `time` to `value`

**Comment by Primajin** [comment]
@NissaCam 
> It's actually already possible to switch between the estimation modes by clicking on the resin icon left to the calculator, but a setting like this would make it more explicit.
> from: @phosphene47
