### ISSUE TITLE
Resin Calculator resets timer when using the subtraction to the right

### ISSUE THREAD

**Issue by ImmortalZypther** [chiyadev/genshin-schedule#5]
When you use the buttons to subtract set amounts of resin, it will reset the timer for the resin regenerating.
![image](https://user-images.githubusercontent.com/21045587/97176500-6ba75500-176b-11eb-99ff-306f6b296fbf.png)

I tested this by matching the resin calculator to my resin in game and then clicking -20 before my resin regenerated in game.
If it kept the timer, it would've regenerated 1 resin in the next minute at most, but it didn't.

**Comment by luaneko** [comment]
These subtraction buttons use the same logic as inputting the resin manually, which automatically assumes you have 8 full minutes until regeneration.

**Comment by ImmortalZypther** [comment]
Is it possible to make it remember the timer instead of resetting to 8 so you don't have to type in the resin once more to make it accurate again?

I noticed it first when I was doing domain runs and it very quickly became off by 2 resin before I had even finished.

**Comment by luaneko** [comment]
Fixed!
