### ISSUE TITLE
Show realm currency steps and sync with the resin estimator

### ISSUE THREAD

**Issue by Primajin** [chiyadev/genshin-schedule#70]
The resin calculator has the great way of switching between time and value based estimation:
<img src="https://user-images.githubusercontent.com/1742115/118258261-f05f8380-b4af-11eb-9636-b3b7d60606f8.png" width="300" /> <img src="https://user-images.githubusercontent.com/1742115/118258263-f0f81a00-b4af-11eb-8dfd-411cb2373056.png" width="300" />

While the recently added realm currency currently only shows one value:
<img src="https://user-images.githubusercontent.com/1742115/118258293-f9e8eb80-b4af-11eb-8984-0732a6715397.png" width="300" />

I would wish for something similar in terms of estimation - at best synced with the setting of resin:
<img src="https://user-images.githubusercontent.com/1742115/118258310-fce3dc00-b4af-11eb-89a4-9c9a5a95dafc.png" width="300" />
(mockup)

_I'll try to take a stab at it._

**Comment by Primajin** [comment]
:construction: WORK IN PROGRESS :construction:

# Too much information?
![tmi](https://user-images.githubusercontent.com/1742115/118264682-56e89f80-b4b8-11eb-8dcf-7cac7bf069ac.png)

![responsive](https://user-images.githubusercontent.com/1742115/118264996-e1310380-b4b8-11eb-993e-89fee1f7fb85.gif)

**Comment by Primajin** [comment]
What do you think @phosphene47? Would this be helpful? How can we make that much info a bit more accessible?
Maybe we only render the first 3 and the last three and then only show the ones in between when a user explicitly clicks on show more?

**Comment by luaneko** [comment]
> What do you think @phosphene47? Would this be helpful? How can we make that much info a bit more accessible?

I definitely think it's way too much information. How about exponentials steps of 2 * 100? i.e. 100, 200, 400, 800, 1600, 2400 (max at trust 10).

**Comment by Primajin** [comment]
Yeah the reasoning behind the step I chose was that all the blueprints you want to buy are either 60, 180, 240 so then you know "ohh in X hours I can finally get that blueprint" - how about we let the user choose what steps they'd like? I'll whip something up after breakfast 🙂

**Comment by Primajin** [comment]
For the other estimator we can then also allow for granulated estimation by X hours

**Comment by Primajin** [comment]
<img src="https://user-images.githubusercontent.com/1742115/118401628-b4225380-b666-11eb-8118-36b7810e981d.png" width=300 />

This looks quite reasonable, what do you think?

**Comment by luaneko** [comment]
> 960 in 36 hours 55 minutes
> 1920 in 73 hours 50 minutes

I think these are better formatted as:

> 960 in 1 day 12 hours 55 minutes
> 1920 in 3 days 1 hour 50 minutes

Also, it's missing the last and most important step which is the estimated time until completion! (2400 in this case; trust rank 10.)

**Comment by Primajin** [comment]
OK here is an updated version:

<img alt="time" title="Realm currency with time steps" width="300" src="https://user-images.githubusercontent.com/1742115/118404850-fe123600-b674-11eb-9740-bceaf42896e5.png" /><img alt="value" title="Realm currency with value steps" width="300" src="https://user-images.githubusercontent.com/1742115/118404853-ff436300-b674-11eb-9179-77671619411b.png" />

I thought it makes sense to show the date if it is more than 24h in the future, what do you think?
Also since realm currency goes in hourly steps and over a longer period, I guess minutes are not needed, right?

I have still a limitation that I couldn't yet wrap my head around - currently the steps are kind of hardcoded multiples of 60 (because blueprint price) starting from 0 - but I guess it would be better to start them from the current value? Otherwise when you have already accumulated some it will show less steps and at some point omits them completely 🤔 

<img alt="limitation" width="300" src="https://user-images.githubusercontent.com/1742115/118404962-84c71300-b675-11eb-9fac-f7e5072bea83.png" />

**Comment by luaneko** [comment]
> I thought it makes sense to show the date if it is more than 24h in the future, what do you think?

Looks good!

>  Also since realm currency goes in hourly steps and over a longer period, I guess minutes are not needed, right?

Yes, I think including minutes would be an unnecessary detail.

> I have still a limitation that I couldn't yet wrap my head around - currently the steps are kind of hardcoded multiples of 60 (because blueprint price) starting from 0 - but I guess it would be better to start them from the current value?

I think keeping it simple and using multiples of 60 is good. It's also consistent with the behavior of resin estimates.

**Comment by Primajin** [comment]
Ohh wait is it 60 or 80?

**Comment by Primajin** [comment]
OK made it steps of 80 - I double checked that that's the correct price.

Removed minutes from time based estimation steps but kept for value based since the next step of 80 could just be around the corner

If that limitation doesn't bother you I'd say this is up for review now 👍🏻
