### ISSUE TITLE
+60 resin button for Transient/Fragile Resin

### ISSUE THREAD

**Issue by ImmortalZypther** [chiyadev/genshin-schedule#84]
Since Transient Resin is easier to get than Fragile Resin, a +60 resin button would be useful to keep the resin synched after you're done setting it.

An alternative would be a box that lets you input a custom amount of resin to add or remove, removing the need for additional buttons in the future.

**Comment by luaneko** [comment]
> Since Transient Resin is easier to get than Fragile Resin, a +60 resin button would be useful to keep the resin synched after you're done setting it.

I'm not sure if we want to introduce any more buttons to the resin calculator. Four is the absolute maximum we can afford and it already looks clunky.

![image](https://user-images.githubusercontent.com/27663662/120071157-4992fe00-c0d1-11eb-9f78-df8f25239c24.png)

> An alternative would be a box that lets you input a custom amount of resin to add or remove, removing the need for additional buttons in the future.

Resin calculator already allows [manual input](https://github.com/chiyadev/genshin-schedule/wiki/Using-the-Resin-Calculator) by clicking on the resin number.

![image](https://user-images.githubusercontent.com/27663662/120071230-a8587780-c0d1-11eb-8281-c77258e2018e.png)

**Comment by ImmortalZypther** [comment]
I knew about that form of manual input, but that also changes the timing of your resin recharge.

The reason the buttons are more useful is them keeping your resin in sync if you've timed it with your actual resin recharging.

**Comment by luaneko** [comment]
I agree that adding a method to manually input resin count (and by extension a `+/-any number` button) without losing timing accuracy would be nice, but I don't think adding more buttons is a good solution in terms of UI and UX.

I'm not sure how to approach this; open to ideas.

**Comment by ImmortalZypther** [comment]
- Replace all the existing buttons with a single input box where you put a number in and then press a + button on the right for adding resin or a - button on the left for subtracting resin
- Keep the buttons for slightly faster inputs for commonly used resin amounts and add the above idea below the buttons
- Have a way to lock the timing of your resin, making any changes afterwards not change that timing, just the resin number you have. For example, if your resin is at 12 and is 10 seconds away from regenerating 1 while locked, changing it to 40 will keep it at 10 seconds rather than resetting to the full 8 minutes.

I personally favor the third idea because it only adds a single button and skips any potential math if you do multiple resin changes in a short amount of time (using fragile, doing a couple bosses, doing a leyline, etc.). All you need to do once it's locked is input the resin you're at by the end, no pressing buttons required.

**Comment by luaneko** [comment]
I merged a PR that allows creating custom resin buttons. I think it's a good compromise between being able to quickly add/subtract a custom amount, and making an input in the calculator that allows add/subtract without losing timing accuracy.

It does bother me that too many buttons can clutter the UI (especially on mobile screens), but that would be on the user adding too many buttons by choice. The default is still four subtraction buttons `-60`, `-40`, `-30`, `-20`.
