### ISSUE TITLE
Request: make map an option

### ISSUE THREAD

**Issue by milan616** [chiyadev/genshin-schedule#9]
It would be great if we could have the map as an option to turn off. I don't use the map and it would use fewer resources in loading into the schedule tracker if it didn't load unless needed by users. On mobile especially since it takes up a large part of the screen.

**Comment by luaneko** [comment]
You can collapse them now!

![image](https://user-images.githubusercontent.com/27663662/97832402-cc63fe00-1d26-11eb-88ae-6d4be3c2b16a.png)

![image](https://user-images.githubusercontent.com/27663662/97832391-c4a45980-1d26-11eb-9010-0a5aa24aa3e0.png)

**Comment by milan616** [comment]
Beautiful, thank you!
